services:
    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
            - "XDG_CONFIG_HOME=/app"
        ports:
            - "8080:80"
        links:
            - php-fpm
            - node

    php-fpm:
        build:
            context: ./docker/php-fpm
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=redis"
        links:
            - mysql
            - node

    php-cli:
        build:
            context: ./
            dockerfile: docker/php-cli.docker
        volumes:
            - ./:/var/www
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
            - "COMPOSER_MEMORY_LIMIT=-1"
        links:
            - mysql
        tty: true

    mysql:
        image: mysql:8.0
        volumes:
            - database:/var/lib
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_USER=user"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=chatapp"
        ports:
            - "33061:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            - PMA_HOST=mysql
            - PMA_USER=user
            - PMA_PASSWORD=secret
            - UPLOAD_LIMIT=64M
        restart: always
        ports:
            - 8081:80
    node:
        image: node:18-alpine
        ports:
            - "3000:3000"
        volumes:
            - ./:/var/www
        working_dir: /var/www
        tty: true

    mongodb:
        image: mongo:latest
        container_name: mongodb
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
            - MONGO_INITDB_DATABASE=chatapp
        ports:
            - "27017:27017"
        volumes:
            - ./docker/data/mongo:/data/db
        restart: always

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=root
            - ME_CONFIG_BASICAUTH_USERNAME=root
            - ME_CONFIG_BASICAUTH_PASSWORD=root
        ports:
            - "8082:8081"
        restart: always
        depends_on:
            - mongodb

volumes:
    database:
